version: '2'

services:
  grafana:
    container_name: nfeweb-grafana
    image: grafana/grafana-oss
    restart: always
    user: $DOCKER_UID:$DOCKER_GID
    ports:
      - 3000:3000
    volumes:
      - /data/nfeweb/nfeweb-grafana/data:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=America/Sao_Paulo

  db:
    container_name: nfeweb-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /data/nfeweb/nfeweb-db/data:/data/pgdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/pgdata

  nfeweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nfeweb
    restart: always
    ports:
      - 8090:8000
    environment:
      DB_HOST: nfeweb-db
      DB_POST: 5432
