version: '3.6'

services:
  grafana:
    container_name: nfeweb-grafana
    image: grafana/grafana-oss:10.0.1
    restart: always
    user: $DOCKER_UID:$DOCKER_GID
#    ports:
#      - 3000:3000
    volumes:
      - /data/nfeweb/nfeweb-grafana/data:/var/lib/grafana
      - /data/nfeweb/nfeweb-grafana/etc:/etc/grafana
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - application
      - database

  db:
    container_name: nfeweb-db
    image: postgres:14.8-bullseye
    restart: always
#    ports:
#      - 5432:5432
    volumes:
      - /data/nfeweb/nfeweb-db/data:/data/pgdata
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/pgdata
    networks:
      - database

  nfeweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nfeweb-api
    restart: always
#    ports:
#      - 8090:8000
    environment:
      DB_HOST: nfeweb-db
      DB_POST: 5432
    networks:
      - application
      - database

  web:
    image: nginx:1.25.1-bookworm
    container_name: nfeweb-nginx
    restart: always
    ports:
      - 8123:8123
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ui:/usr/share/nginx/html/ui:ro
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - web
      - application


networks:
  web: {}
  application: {}
  database: {}