# Generated by Django 4.0.6 on 2022-07-23 15:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDbModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line1', models.CharField(max_length=100, null=True)),
                ('line2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='NfeConsumerDbModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identification', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'nfe_consumer',
            },
        ),
        migrations.CreateModel(
            name='NfeDbModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_date', models.DateTimeField()),
                ('access_key', models.CharField(max_length=255, unique=True)),
                ('total_amount', models.FloatField()),
                ('total_discounts', models.FloatField()),
                ('raw_html', models.TextField()),
                ('url', models.URLField()),
                ('payment_type', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('MONEY', 'Money'), ('STORE_CARD', 'Store Card')], max_length=20)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumer', to='api.nfeconsumerdbmodel')),
            ],
            options={
                'db_table': 'nfe',
            },
        ),
        migrations.CreateModel(
            name='ProductDbModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('metric_unit', models.CharField(choices=[('KG', 'KG'), ('UNIT', 'UNIT')], max_length=10)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='NfeIssuerDbModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('national_registration_code', models.CharField(max_length=255)),
                ('state_registration_code', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfe_issue', to='api.addressdbmodel')),
            ],
            options={
                'db_table': 'nfe_issuer',
            },
        ),
        migrations.CreateModel(
            name='NfeEntryDbModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField()),
                ('unitary_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('nfe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='api.nfedbmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfe_entries', to='api.productdbmodel')),
            ],
            options={
                'db_table': 'nfe_entry',
            },
        ),
        migrations.AddField(
            model_name='nfedbmodel',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfes', to='api.nfeissuerdbmodel'),
        ),
    ]
