# Generated by Django 4.0.6 on 2022-07-25 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productcategory_productdbmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdbmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.productcategory'),
        ),
    ]
