# Generated by Django 4.0.6 on 2022-07-25 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_productdbmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdbmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='api.productcategory'),
        ),
    ]
