# Generated by Django 4.1 on 2022-08-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_productdbmodel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfedbmodel",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("CREDIT_CARD", "Credit Card"),
                    ("DEBIT_CARD", "Debit Card"),
                    ("MONEY", "Money"),
                    ("STORE_CARD", "Store Card"),
                    ("FOOD_VOUCHER", "Food Voucher"),
                ],
                max_length=20,
            ),
        ),
    ]
