# Generated by Django 4.1.4 on 2023-01-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_nfedbmodel_payment_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nfeissuerdbmodel",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="productdbmodel",
            options={"ordering": ["description"]},
        ),
    ]
