# Generated by Django 4.1.4 on 2023-01-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_nfeissuerdbmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nfedbmodel",
            options={"ordering": ["-created_at"]},
        ),
    ]
