# Generated by Django 4.1.4 on 2023-01-21 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_nfedbmodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfedbmodel",
            name="consumer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumer",
                to="api.nfeconsumerdbmodel",
            ),
        ),
        migrations.AlterField(
            model_name="nfedbmodel",
            name="issuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nfes",
                to="api.nfeissuerdbmodel",
            ),
        ),
        migrations.AlterField(
            model_name="nfeentrydbmodel",
            name="nfe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="api.nfedbmodel",
            ),
        ),
        migrations.AlterField(
            model_name="nfeissuerdbmodel",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nfe_issue",
                to="api.addressdbmodel",
            ),
        ),
    ]
