# Generated by Django 4.1.4 on 2023-02-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_nfedbmodel_consumer_alter_nfedbmodel_issuer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfedbmodel",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("CREDIT_CARD", "Credit Card"),
                    ("DEBIT_CARD", "Debit Card"),
                    ("MONEY", "Money"),
                    ("STORE_CARD", "Store Card"),
                    ("FOOD_VOUCHER", "Food Voucher"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
