# Generated by Django 4.1.4 on 2023-02-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_productcategory_parent_alter_productdbmodel_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producttype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelTable(
            name="producttype",
            table="product_type",
        ),
    ]
