# Generated by Django 4.1.4 on 2023-02-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_producttype_options_alter_producttype_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
