# Generated by Django 4.1.4 on 2023-02-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_producttype_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productdbmodel",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="productdbmodel",
            old_name="description",
            new_name="name",
        ),
    ]
