# Generated by Django 4.1.4 on 2023-02-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_productdbmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdbmodel",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="productdbmodel",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
