# Generated by Django 4.1.4 on 2023-02-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_productdbmodel_description_alter_productdbmodel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdbmodel",
            name="category",
        ),
    ]
