# Generated by Django 4.2.6 on 2023-10-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_productdbmodel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfeissuerdbmodel",
            name="state_registration_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
